// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/4/2569 19:32:24
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["D:/Developer/twitch-overlay/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Developer/twitch-overlay/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Developer/twitch-overlay/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Developer/twitch-overlay/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Developer/twitch-overlay/plugins/**/*.{js,ts,mjs}","D:/Developer/twitch-overlay/composables/**/*.{js,ts,mjs}","D:/Developer/twitch-overlay/utils/**/*.{js,ts,mjs}","D:/Developer/twitch-overlay/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Developer/twitch-overlay/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/Developer/twitch-overlay/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/Developer/twitch-overlay/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;