// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 4/16/2026, 5:45:43 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/Users/Suchanat.K/Stream Chat Demo/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Suchanat.K/Stream Chat Demo/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Suchanat.K/Stream Chat Demo/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Suchanat.K/Stream Chat Demo/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Suchanat.K/Stream Chat Demo/plugins/**/*.{js,ts,mjs}","C:/Users/Suchanat.K/Stream Chat Demo/composables/**/*.{js,ts,mjs}","C:/Users/Suchanat.K/Stream Chat Demo/utils/**/*.{js,ts,mjs}","C:/Users/Suchanat.K/Stream Chat Demo/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Suchanat.K/Stream Chat Demo/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Suchanat.K/Stream Chat Demo/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Suchanat.K/Stream Chat Demo/app.config.{js,ts,mjs}","C:/Users/Suchanat.K/Stream Chat Demo/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;